#!/usr/bin/env bash
# Submit generated WinGet manifests to microsoft/winget-pkgs through a fork.
# Idempotent: an open pull request for the same version is left alone.
#
# Usage: publish-winget.sh --fork owner/winget-pkgs --manifests dist/winget/manifests
#          --identifier IdylLabs.Purlview --version 0.2.0
# Environment: GH_TOKEN of an account that can push to the fork and open
#              pull requests on microsoft/winget-pkgs.
set -euo pipefail

FORK=""; MANIFESTS=""; IDENTIFIER=""; VERSION=""; UPSTREAM="microsoft/winget-pkgs"
while [ $# -gt 0 ]; do
  case "$1" in
    --fork) FORK="$2"; shift 2 ;;
    --manifests) MANIFESTS="$2"; shift 2 ;;
    --identifier) IDENTIFIER="$2"; shift 2 ;;
    --version) VERSION="$2"; shift 2 ;;
    --upstream) UPSTREAM="$2"; shift 2 ;;
    *) echo "publish-winget: unknown argument $1" >&2; exit 2 ;;
  esac
done
[[ -n "$FORK" && -n "$MANIFESTS" && -n "$IDENTIFIER" && -n "$VERSION" ]] || { echo "usage: publish-winget.sh --fork --manifests --identifier --version" >&2; exit 2; }
rel="manifests/$(tr '[:upper:]' '[:lower:]' <<<"${IDENTIFIER:0:1}")/${IDENTIFIER//./\/}/$VERSION"
src="$MANIFESTS/${rel#manifests/}"
[[ -d "$src" ]] || { echo "publish-winget: generated manifests not found at $src" >&2; exit 1; }

title="New version: $IDENTIFIER version $VERSION"
existing="$(gh pr list --repo "$UPSTREAM" --search "\"$title\" in:title" --state open --json number,url --jq '.[0].url' 2>/dev/null || true)"
if [[ -n "$existing" ]]; then echo "publish-winget: pull request already open: $existing"; exit 0; fi
if gh api "repos/$UPSTREAM/contents/$rel" >/dev/null 2>&1; then echo "publish-winget: $IDENTIFIER $VERSION already exists upstream"; exit 0; fi

branch="purlview-$VERSION"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
git -c credential.helper='!gh auth git-credential' clone --quiet --depth 1 "https://github.com/$FORK.git" "$WORK/repo"
cd "$WORK/repo"
git remote add upstream "https://github.com/$UPSTREAM.git"
git fetch --quiet --depth 1 upstream master
git checkout --quiet -B "$branch" upstream/master
mkdir -p "$rel"
# The schema header must be the first line; drop GoReleaser's generated-file comment.
for f in "$src"/*.yaml; do sed '1{/^# This file was generated by GoReleaser/d;}' "$f" >"$rel/$(basename "$f")"; done
git add "$rel"
git -c user.name='purlview-release' -c user.email='41898282+github-actions[bot]@users.noreply.github.com' commit --quiet -m "$title"
git -c credential.helper='!gh auth git-credential' push --quiet --force origin "$branch"
url="$(gh pr create --repo "$UPSTREAM" --head "${FORK%%/*}:$branch" --base master --title "$title" --body "Automated submission from the Purlview release workflow.")"
echo "publish-winget: opened $url"
